name: Package PrestaShop Module and Create Release

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Package module
        run: |
          module_name=$(basename $(pwd))
          zip -r "${module_name}.zip" . -x ".git/*" ".github/*" "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: prestashop-module
          path: ./*.zip

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install release-drafter
        run: npm install --global release-drafter

      - name: Draft a new release
        run: release-drafter --version-template "v$NEXT_PATCH_VERSION"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
