name: Package PrestaShop Module and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Package module
        run: |
          module_name=$(basename $(pwd))
          zip -r "${module_name}.zip" . -x ".git/*" ".github/*" "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: prestashop-module
          path: ./*.zip

      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
